In [1]:
pip install duckdb

Requirement already satisfied: duckdb in /opt/anaconda3/lib/python3.13/site-packages (1.5.5)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install requests

Requirement already satisfied: requests in /opt/anaconda3/lib/python3.13/site-packages (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests) (2026.7.22)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np 
import pandas as pd

In [4]:
import requests
import json

In [5]:
url = "https://api.worldbank.org/v2/country?format=json&per_page=300"
response = requests.get(url)
countries = response.json()[1]

In [6]:
# check the HTTP status. 200 means success.
print("Status code:", response.status_code)

Status code: 200

In [7]:
# turn the raw response into Python objects
real = [c for c in countries if c["region"]["value"] != "Aggregates"]
agg  = [c for c in countries if c["region"]["value"] == "Aggregates"]

In [8]:
print("Real countries:", len(real))
print("Aggregates:", len(agg))

Real countries: 217
Aggregates: 79

In [9]:
with open("countries_real.json", "w") as f:
    json.dump(real, f)

In [10]:
print("Saved", len(real), "countries")

Saved 217 countries

In [11]:
import os
print(os.path.exists("countries_real.json"))
print(os.path.getsize("countries_real.json"), "bytes")

True
95134 bytes

In [12]:
#  Fetching indicators
base = "https://api.worldbank.org/v2/indicator?format=json&per_page=5000"

all_inds = []
r = requests.get(base + "&page=1")
meta = r.json()[0]
all_inds.extend(r.json()[1])
pages = meta["pages"]
print("Pages:", pages, "| page 1:", len(all_inds))
for p in range(2, pages + 1):
    chunk = requests.get(base + f"&page={p}").json()[1]
    all_inds.extend(chunk)
    print(f"page {p}: {len(chunk)}")

print("Total:", len(all_inds))

Pages: 6 | page 1: 5000
page 2: 5000
page 3: 5000
page 4: 5000
page 5: 5000
page 6: 4544
Total: 29544

In [13]:
import csv

with open("indicators_catalog.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(["indicator_id", "indicator_name", "definition", "source"])
    for ind in all_inds:
        writer.writerow([
            ind.get("id", ""),
            ind.get("name", ""),
            ind.get("sourceNote", ""),
            ind.get("source", {}).get("value", "")
        ])

print("Wrote indicators_catalog.csv with", len(all_inds), "rows")

Wrote indicators_catalog.csv with 29544 rows

In [14]:
import pandas as pd
df_ind = pd.read_csv("indicators_catalog.csv")
print(df_ind.shape)
print(df_ind["source"].value_counts().head(10))

(29544, 4)
source
Education Statistics                                                   8317
The Atlas of Social Protection: Indicators of Resilience and Equity    3561
Global Findex database                                                 2947
Quarterly External Debt Statistics SDDS                                1800
Disability Data Hub (DDH)                                              1577
World Development Indicators                                           1499
WDI Database Archives                                                  1017
Gender Statistics                                                       948
Africa Development Indicators                                           837
Global Jobs Indicators Database (JOIN)                                  746
Name: count, dtype: int64

In [15]:
wdi = df_ind[df_ind["source"] == "World Development Indicators"].copy()
print(wdi.shape)
print(wdi.head())

(1499, 4)
           indicator_id                                     indicator_name  \
1337  AG.CON.FERT.PT.ZS  Fertilizer consumption (% of fertilizer produc...
1338     AG.CON.FERT.ZS  Fertilizer consumption (kilograms per hectare ...
1358     AG.LND.AGRI.K2                         Agricultural land (sq. km)
1359     AG.LND.AGRI.ZS                 Agricultural land (% of land area)
1360     AG.LND.ARBL.HA                             Arable land (hectares)

                                             definition  \
1337  Fertilizer consumption measures the quantity o...
1338  Fertilizer consumption measures the quantity o...
1358  Agricultural land refers to the land area that...
1359  Agricultural land refers to the share of land ...
1360  Arable land (in hectares) includes land define...

                            source
1337  World Development Indicators
1338  World Development Indicators
1358  World Development Indicators
1359  World Development Indicators
1360  World Development Indicators

In [16]:
keywords = [
    "Individuals using the Internet",
    "Fixed broadband subscriptions",
    "Mobile cellular subscriptions",
    "Secure Internet servers",
    "ICT service exports",
    "Investment in ICT with private participation",
    "Account ownership at a financial institution",
    "GDP per person employed",
    "Labor force participation rate, female",
    "Ratio of female to male labor force participation",
    "GDP per capita, PPP",
    "School enrollment, tertiary",
    "Trade (% of GDP)",
    "Urban population",
    "Access to electricity",
    "Government effectiveness",
    "Regulatory quality",
]

for kw in keywords:
    hits = wdi[wdi["indicator_name"].str.contains(kw, case=False, na=False)]
    print(f"--- {kw} ({len(hits)} hits)")
    for _, r in hits.iterrows():
        print("   ", r["indicator_id"], "|", r["indicator_name"])

--- Individuals using the Internet (3 hits)
    IT.NET.USER.FE.ZS | Individuals using the Internet, female (% of female population)
    IT.NET.USER.MA.ZS | Individuals using the Internet, male (% of male population)
    IT.NET.USER.ZS | Individuals using the Internet (% of population)
--- Fixed broadband subscriptions (2 hits)
    IT.NET.BBND | Fixed broadband subscriptions
    IT.NET.BBND.P2 | Fixed broadband subscriptions (per 100 people)
--- Mobile cellular subscriptions (2 hits)
    IT.CEL.SETS | Mobile cellular subscriptions
    IT.CEL.SETS.P2 | Mobile cellular subscriptions (per 100 people)
--- Secure Internet servers (2 hits)
    IT.NET.SECR | Secure Internet servers
    IT.NET.SECR.P6 | Secure Internet servers (per 1 million people)
--- ICT service exports (2 hits)
    BX.GSR.CCIS.CD | ICT service exports (BoP, current US$)
    BX.GSR.CCIS.ZS | ICT service exports (% of service exports, BoP)
--- Investment in ICT with private participation (1 hits)
    IE.PPI.ICTI.CD | Investment in ICT with private participation (current US$)
--- Account ownership at a financial institution (9 hits)
    FX.OWN.TOTL.40.ZS | Account ownership at a financial institution or with a mobile-money-service provider, poorest 40% (% of population ages 15+)
    FX.OWN.TOTL.60.ZS | Account ownership at a financial institution or with a mobile-money-service provider, richest 60% (% of population ages 15+)
    FX.OWN.TOTL.FE.ZS | Account ownership at a financial institution or with a mobile-money-service provider, female (% of population ages 15+)
    FX.OWN.TOTL.MA.ZS | Account ownership at a financial institution or with a mobile-money-service provider, male (% of population ages 15+)
    FX.OWN.TOTL.OL.ZS | Account ownership at a financial institution or with a mobile-money-service provider, older adults (% of population ages 25+)
    FX.OWN.TOTL.PL.ZS | Account ownership at a financial institution or with a mobile-money-service provider, primary education or less (% of population ages 15+)
    FX.OWN.TOTL.SO.ZS | Account ownership at a financial institution or with a mobile-money-service provider, secondary education or more (% of population ages 15+)
    FX.OWN.TOTL.YG.ZS | Account ownership at a financial institution or with a mobile-money-service provider, young adults (% of population ages 15-24)
    FX.OWN.TOTL.ZS | Account ownership at a financial institution or with a mobile-money-service provider (% of population ages 15+)
--- GDP per person employed (1 hits)
    SL.GDP.PCAP.EM.KD | GDP per person employed (constant 2021 PPP $)
--- Labor force participation rate, female (3 hits)
    SL.TLF.ACTI.FE.ZS | Labor force participation rate, female (% of female population ages 15-64) (modeled ILO estimate)
    SL.TLF.CACT.FE.NE.ZS | Labor force participation rate, female (% of female population ages 15+) (national estimate)
    SL.TLF.CACT.FE.ZS | Labor force participation rate, female (% of female population ages 15+) (modeled ILO estimate)
--- Ratio of female to male labor force participation (2 hits)
    SL.TLF.CACT.FM.NE.ZS | Ratio of female to male labor force participation rate (%) (national estimate)
    SL.TLF.CACT.FM.ZS | Ratio of female to male labor force participation rate (%) (modeled ILO estimate)
--- GDP per capita, PPP (2 hits)
    NY.GDP.PCAP.PP.CD | GDP per capita, PPP (current international $)
    NY.GDP.PCAP.PP.KD | GDP per capita, PPP (constant 2021 international $)
--- School enrollment, tertiary (4 hits)
    SE.ENR.TERT.FM.ZS | School enrollment, tertiary (gross), gender parity index (GPI)
    SE.TER.ENRR | School enrollment, tertiary (% gross)
    SE.TER.ENRR.FE | School enrollment, tertiary, female (% gross)
    SE.TER.ENRR.MA | School enrollment, tertiary, male (% gross)
--- Trade (% of GDP) (0 hits)
--- Urban population (14 hits)
    EG.CFT.ACCS.UR.ZS | Access to clean fuels and technologies for cooking, urban (% of urban population)
    EG.ELC.ACCS.UR.ZS | Access to electricity, urban (% of urban population)
    EN.POP.EL5M.UR.ZS | Urban population living in areas where elevation is below 5 meters (% of total population)
    EN.POP.SLUM.UR.ZS | Population living in slums (% of urban population)
    EN.URB.LCTY.UR.ZS | Population in the largest city (% of urban population)
    SH.H2O.BASW.UR.ZS | People using at least basic drinking water services, urban (% of urban population)
    SH.H2O.SMDW.UR.ZS | People using safely managed drinking water services, urban (% of urban population)
    SH.STA.BASS.UR.ZS | People using at least basic sanitation services, urban (% of urban population)
    SH.STA.HYGN.UR.ZS | People with basic handwashing facilities including soap and water, urban (% of urban population)
    SH.STA.ODFC.UR.ZS | People practicing open defecation, urban (% of urban population)
    SH.STA.SMSS.UR.ZS | People using safely managed sanitation services, urban (% of urban population)
    SP.URB.GROW | Urban population growth (annual %)
    SP.URB.TOTL | Urban population
    SP.URB.TOTL.IN.ZS | Urban population (% of total population)
--- Access to electricity (3 hits)
    EG.ELC.ACCS.RU.ZS | Access to electricity, rural (% of rural population)
    EG.ELC.ACCS.UR.ZS | Access to electricity, urban (% of urban population)
    EG.ELC.ACCS.ZS | Access to electricity (% of population)
--- Government effectiveness (2 hits)
    GOV_WGI_GE_EST | Government Effectiveness - Governance estimate (approx. -2.5 to +2.5)
    GOV_WGI_GE_SC | Government Effectiveness - Governance score (0-100)
--- Regulatory quality (2 hits)
    GOV_WGI_RQ_EST | Regulatory Quality - Governance estimate (approx. -2.5 to +2.5)
    GOV_WGI_RQ_SC | Regulatory Quality - Governance score (0-100)

/var/folders/6v/s9_yhnl534n43tphxkf70pxh0000gn/T/ipykernel_41229/3880633887.py:22: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  hits = wdi[wdi["indicator_name"].str.contains(kw, case=False, na=False)]

In [17]:
import re

wdi[wdi["indicator_name"].str.contains(re.escape("Trade (% of GDP)"), case=False, na=False)][["indicator_id", "indicator_name"]]

            indicator_id                indicator_name
15837     NE.TRD.GNFS.ZS              Trade (% of GDP)
27089  TG.VAL.TOTL.GD.ZS  Merchandise trade (% of GDP)

In [18]:
wdi[wdi["indicator_id"].isin(["GOV_WGI_GE_EST", "FX.OWN.TOTL.ZS", "IT.NET.USER.ZS", "SL.TLF.CACT.FE.ZS"])][["indicator_id", "indicator_name", "source"]]

,indicator_id,indicator_name,source
11117,FX.OWN.TOTL.ZS,Account ownership at a financial institution o...,World Development Indicators
11666,GOV_WGI_GE_EST,Government Effectiveness - Governance estimate...,World Development Indicators
13546,IT.NET.USER.ZS,Individuals using the Internet (% of population),World Development Indicators
26387,SL.TLF.CACT.FE.ZS,"Labor force participation rate, female (% of f...",World Development Indicators

In [19]:
shortlist = [
    "IT.NET.USER.ZS", "IT.NET.USER.FE.ZS", "IT.NET.USER.MA.ZS",
    "IT.NET.BBND.P2", "IT.CEL.SETS.P2", "IT.NET.SECR.P6",
    "BX.GSR.CCIS.ZS", "IE.PPI.ICTI.CD",
    "FX.OWN.TOTL.ZS", "FX.OWN.TOTL.FE.ZS",
    "SL.GDP.PCAP.EM.KD", "SL.TLF.CACT.FE.ZS", "SL.TLF.CACT.FM.ZS",
    "NY.GDP.PCAP.PP.KD", "SE.TER.ENRR", "NE.TRD.GNFS.ZS",
    "SP.URB.TOTL.IN.ZS", "EG.ELC.ACCS.ZS",
    "GOV_WGI_GE_EST", "GOV_WGI_RQ_EST",
]

with open("shortlist_codes.txt", "w") as f:
    f.write("\n".join(shortlist))

print(len(shortlist), "codes saved")

20 codes saved

In [20]:
import time

with open("countries_real.json") as f:
    countries = json.load(f)
country_codes = [c["id"] for c in countries]

shortlist = [
    "IT.NET.USER.ZS", "IT.NET.USER.FE.ZS", "IT.NET.USER.MA.ZS",
    "IT.NET.BBND.P2", "IT.CEL.SETS.P2", "IT.NET.SECR.P6",
    "BX.GSR.CCIS.ZS", "IE.PPI.ICTI.CD",
    "FX.OWN.TOTL.ZS", "FX.OWN.TOTL.FE.ZS",
    "SL.GDP.PCAP.EM.KD", "SL.TLF.CACT.FE.ZS", "SL.TLF.CACT.FM.ZS",
    "NY.GDP.PCAP.PP.KD", "SE.TER.ENRR", "NE.TRD.GNFS.ZS",
    "SP.URB.TOTL.IN.ZS", "EG.ELC.ACCS.ZS",
    "GOV_WGI_GE_EST", "GOV_WGI_RQ_EST",
]

all_rows = []

for code in shortlist:
    url = f"https://api.worldbank.org/v2/country/all/indicator/{code}?format=json&per_page=20000&date=1990:2025"
    r = requests.get(url)
    if r.status_code != 200:
        print(code, "failed", r.status_code)
        continue
    data = r.json()
    if len(data) < 2 or data[1] is None:
        print(code, "no data")
        continue
    rows = data[1]
    print(f"{code}: {len(rows)} of {data[0]['total']}")
    for row in rows:
        if row["countryiso3code"] in country_codes and row["value"] is not None:
            all_rows.append({
                "country": row["countryiso3code"],
                "year": int(row["date"]),
                "indicator": row["indicator"]["id"],
                "value": row["value"]
            })
    time.sleep(0.3)

df_long = pd.DataFrame(all_rows)
df_long.to_csv("panel_long.csv", index=False)
print("Total observations:", len(df_long))

IT.NET.USER.ZS: 9576 of 9576
IT.NET.USER.FE.ZS: 9576 of 9576
IT.NET.USER.MA.ZS: 9576 of 9576
IT.NET.BBND.P2: 9576 of 9576
IT.CEL.SETS.P2: 9576 of 9576
IT.NET.SECR.P6: 9576 of 9576
BX.GSR.CCIS.ZS: 9576 of 9576
IE.PPI.ICTI.CD: 9576 of 9576
FX.OWN.TOTL.ZS: 9576 of 9576
FX.OWN.TOTL.FE.ZS: 9576 of 9576
SL.GDP.PCAP.EM.KD: 9576 of 9576
SL.TLF.CACT.FE.ZS: 9576 of 9576
SL.TLF.CACT.FM.ZS: 9576 of 9576
NY.GDP.PCAP.PP.KD: 9576 of 9576
SE.TER.ENRR: 9576 of 9576
NE.TRD.GNFS.ZS: 9576 of 9576
SP.URB.TOTL.IN.ZS: 9576 of 9576
EG.ELC.ACCS.ZS: 9576 of 9576
GOV_WGI_GE_EST: 9576 of 9576
GOV_WGI_RQ_EST: 9576 of 9576
Total observations: 92105

In [21]:
df_long = pd.read_csv("panel_long.csv")
print(df_long.shape)
print(df_long["indicator"].value_counts())

(92105, 4)
indicator
SP.URB.TOTL.IN.ZS    7812
IT.CEL.SETS.P2       7029
NY.GDP.PCAP.PP.KD    6977
EG.ELC.ACCS.ZS       6747
SL.TLF.CACT.FE.ZS    6718
SL.TLF.CACT.FM.ZS    6718
IT.NET.USER.ZS       6224
NE.TRD.GNFS.ZS       6134
SL.GDP.PCAP.EM.KD    6119
GOV_WGI_RQ_EST       5374
GOV_WGI_GE_EST       5373
BX.GSR.CCIS.ZS       5073
IT.NET.BBND.P2       4330
SE.TER.ENRR          3863
IT.NET.SECR.P6       3193
IT.NET.USER.MA.ZS    1363
IT.NET.USER.FE.ZS    1362
FX.OWN.TOTL.ZS        705
FX.OWN.TOTL.FE.ZS     679
IE.PPI.ICTI.CD        312
Name: count, dtype: int64

In [22]:
df_long["year"] = df_long["year"].astype(int)

for code in ["IT.NET.USER.FE.ZS", "IT.NET.USER.MA.ZS", "FX.OWN.TOTL.FE.ZS", "IT.NET.USER.ZS", "SL.TLF.CACT.FE.ZS", "SL.GDP.PCAP.EM.KD"]:
    sub = df_long[df_long["indicator"] == code]
    print("---", code, "| countries:", sub["country"].nunique(), "| years:", sub["year"].min(), "-", sub["year"].max())
    print(sub.groupby("year")["country"].count().tail(15))

--- IT.NET.USER.FE.ZS | countries: 137 | years: 2000 - 2025
year
2011    51
2012    59
2013    67
2014    73
2015    78
2016    76
2017    92
2018    82
2019    92
2020    74
2021    77
2022    70
2023    67
2024    65
2025     7
Name: country, dtype: int64
--- IT.NET.USER.MA.ZS | countries: 137 | years: 2000 - 2025
year
2011    51
2012    59
2013    68
2014    73
2015    78
2016    76
2017    92
2018    82
2019    92
2020    74
2021    77
2022    70
2023    67
2024    65
2025     7
Name: country, dtype: int64
--- FX.OWN.TOTL.FE.ZS | countries: 159 | years: 2011 - 2024
year
2011    126
2014    135
2017    143
2021    120
2022     16
2024    139
Name: country, dtype: int64
--- IT.NET.USER.ZS | countries: 213 | years: 1990 - 2025
year
2011    204
2012    203
2013    201
2014    201
2015    201
2016    203
2017    200
2018    182
2019    189
2020    184
2021    180
2022    182
2023    181
2024    182
2025     10
Name: country, dtype: int64
--- SL.TLF.CACT.FE.ZS | countries: 187 | years: 1990 - 2025
year
2011    187
2012    187
2013    187
2014    187
2015    187
2016    187
2017    187
2018    187
2019    187
2020    187
2021    187
2022    186
2023    184
2024    182
2025    182
Name: country, dtype: int64
--- SL.GDP.PCAP.EM.KD | countries: 177 | years: 1991 - 2025
year
2011    176
2012    176
2013    177
2014    177
2015    177
2016    177
2017    177
2018    177
2019    177
2020    177
2021    177
2022    176
2023    172
2024    171
2025    168
Name: country, dtype: int64

In [23]:
df_long["year"] = df_long["year"].astype(int)

key = [
    "IT.NET.USER.ZS", "IT.NET.USER.FE.ZS", "IT.NET.USER.MA.ZS",
    "SL.GDP.PCAP.EM.KD", "SL.TLF.CACT.FE.ZS",
    "NY.GDP.PCAP.PP.KD", "SE.TER.ENRR", "NE.TRD.GNFS.ZS",
    "SP.URB.TOTL.IN.ZS", "EG.ELC.ACCS.ZS",
    "GOV_WGI_GE_EST", "GOV_WGI_RQ_EST",
]

wide = df_long[df_long["indicator"].isin(key)].pivot_table(
    index=["country", "year"], columns="indicator", values="value"
).reset_index()

for lo, hi in [(2011, 2023), (2011, 2024), (2015, 2024), (2017, 2024)]:
    sub = wide[(wide["year"] >= lo) & (wide["year"] <= hi)].dropna()
    print(f"{lo}-{hi}: rows={len(sub)}, countries={sub['country'].nunique()}, mean years/country={len(sub)/max(sub['country'].nunique(),1):.1f}")

2011-2023: rows=837, countries=106, mean years/country=7.9
2011-2024: rows=876, countries=107, mean years/country=8.2
2015-2024: rows=671, countries=107, mean years/country=6.3
2017-2024: rows=532, countries=105, mean years/country=5.1

In [24]:
import pandas as pd
df_long["year"] = df_long["year"].astype(int)

key = [
    "IT.NET.USER.ZS", "IT.NET.USER.FE.ZS", "IT.NET.USER.MA.ZS",
    "SL.GDP.PCAP.EM.KD", "SL.TLF.CACT.FE.ZS",
    "NY.GDP.PCAP.PP.KD", "SE.TER.ENRR", "NE.TRD.GNFS.ZS",
    "SP.URB.TOTL.IN.ZS", "EG.ELC.ACCS.ZS",
    "GOV_WGI_GE_EST", "GOV_WGI_RQ_EST",
]

wide = df_long[df_long["indicator"].isin(key)].pivot_table(
    index=["country", "year"], columns="indicator", values="value"
).reset_index()

window = wide[(wide["year"] >= 2011) & (wide["year"] <= 2024)].dropna()
window.to_csv("panel_window_2011_2024.csv", index=False)
print("saved:", window.shape)

coverage = df_long.groupby("indicator").agg(
    n_obs=("value", "count"),
    n_countries=("country", "nunique"),
    year_min=("year", "min"),
    year_max=("year", "max"),
).sort_values("n_obs", ascending=False)
coverage.to_csv("coverage_by_indicator.csv")
print(coverage)

saved: (876, 14)
                   n_obs  n_countries  year_min  year_max
indicator
SP.URB.TOTL.IN.ZS   7812          217      1990      2025
IT.CEL.SETS.P2      7029          214      1990      2024
NY.GDP.PCAP.PP.KD   6977          199      1990      2025
EG.ELC.ACCS.ZS      6747          216      1990      2024
SL.TLF.CACT.FM.ZS   6718          187      1990      2025
SL.TLF.CACT.FE.ZS   6718          187      1990      2025
IT.NET.USER.ZS      6224          213      1990      2025
NE.TRD.GNFS.ZS      6134          193      1990      2025
SL.GDP.PCAP.EM.KD   6119          177      1991      2025
GOV_WGI_RQ_EST      5374          205      1996      2025
GOV_WGI_GE_EST      5373          205      1996      2025
BX.GSR.CCIS.ZS      5073          190      1990      2025
IT.NET.BBND.P2      4330          208      1998      2024
SE.TER.ENRR         3863          200      1990      2025
IT.NET.SECR.P6      3193          215      2010      2024
IT.NET.USER.MA.ZS   1363          137      2000      2025
IT.NET.USER.FE.ZS   1362          137      2000      2025
FX.OWN.TOTL.ZS       705          161      2011      2024
FX.OWN.TOTL.FE.ZS    679          159      2011      2024
IE.PPI.ICTI.CD       312          111      1990      2024

In [25]:
# PARKED: Task 0 redo from scratch
# Goal: rebuild the whole Task 0 pipeline without hints.
# Files to reproduce:
#   countries_real.json
#   indicators_catalog.csv
#   shortlist_codes.txt
#   panel_long.csv
#   panel_window_2011_2024.csv
#   coverage_by_indicator.csv
# Key gotchas I hit:
#   - API default per_page = 50, must set higher
#   - API default returns latest value per country, must add &date=1990:2025
#   - Indicator catalog is paginated, loop pages
#   - country/region field: exclude region == "Aggregates"
#   - countryiso3code not country.id
# Attempt date: Oct 11

In [26]:
rows = []
for kw in keywords:
    hits = wdi[wdi["indicator_name"].str.contains(re.escape(kw), case=False, na=False)]
    for _, r in hits.iterrows():
        rows.append({
            "keyword": kw,
            "code": r["indicator_id"],
            "name": r["indicator_name"],
            "decision": "keep" if r["indicator_id"] in shortlist else "drop",
        })

decisions = pd.DataFrame(rows)
print(decisions.shape)
print(decisions.head(15).to_string())

(56, 4)
                                         keyword               code                                                                                                                          name decision
0                 Individuals using the Internet  IT.NET.USER.FE.ZS                                                               Individuals using the Internet, female (% of female population)     keep
1                 Individuals using the Internet  IT.NET.USER.MA.ZS                                                                   Individuals using the Internet, male (% of male population)     keep
2                 Individuals using the Internet     IT.NET.USER.ZS                                                                              Individuals using the Internet (% of population)     keep
3                  Fixed broadband subscriptions        IT.NET.BBND                                                                                                 Fixed broadband subscriptions     drop
4                  Fixed broadband subscriptions     IT.NET.BBND.P2                                                                                Fixed broadband subscriptions (per 100 people)     keep
5                  Mobile cellular subscriptions        IT.CEL.SETS                                                                                                 Mobile cellular subscriptions     drop
6                  Mobile cellular subscriptions     IT.CEL.SETS.P2                                                                                Mobile cellular subscriptions (per 100 people)     keep
7                        Secure Internet servers        IT.NET.SECR                                                                                                       Secure Internet servers     drop
8                        Secure Internet servers     IT.NET.SECR.P6                                                                                Secure Internet servers (per 1 million people)     keep
9                            ICT service exports     BX.GSR.CCIS.CD                                                                                        ICT service exports (BoP, current US$)     drop
10                           ICT service exports     BX.GSR.CCIS.ZS                                                                               ICT service exports (% of service exports, BoP)     keep
11  Investment in ICT with private participation     IE.PPI.ICTI.CD                                                                    Investment in ICT with private participation (current US$)     keep
12  Account ownership at a financial institution  FX.OWN.TOTL.40.ZS  Account ownership at a financial institution or with a mobile-money-service provider, poorest 40% (% of population ages 15+)     drop
13  Account ownership at a financial institution  FX.OWN.TOTL.60.ZS  Account ownership at a financial institution or with a mobile-money-service provider, richest 60% (% of population ages 15+)     drop
14  Account ownership at a financial institution  FX.OWN.TOTL.FE.ZS       Account ownership at a financial institution or with a mobile-money-service provider, female (% of population ages 15+)     keep

In [27]:
print(decisions["decision"].value_counts())

decision
drop    36
keep    20
Name: count, dtype: int64

In [28]:
reasons = {
    # --- Keeps: adoption ---
    "IT.NET.USER.ZS":     "Total internet penetration. Primary digital adoption measure.",
    "IT.NET.USER.FE.ZS":  "Female internet penetration. Required to construct the gender gap.",
    "IT.NET.USER.MA.ZS":  "Male internet penetration. Required to construct the gender gap.",
    "IT.NET.BBND.P2":     "Fixed broadband per 100. Rate form for cross-country comparability.",
    "IT.CEL.SETS.P2":     "Mobile subscriptions per 100. Rate form for cross-country comparability.",
    "IT.NET.SECR.P6":     "Secure servers per 1m. Rate form for cross-country comparability.",
    "BX.GSR.CCIS.ZS":     "ICT service exports as share of service exports. Scale-free, comparable.",
    "IE.PPI.ICTI.CD":     "ICT investment with private participation. Only available variant.",

    # --- Keeps: inclusion ---
    "FX.OWN.TOTL.ZS":     "Account ownership, population 15+. Total aggregate.",
    "FX.OWN.TOTL.FE.ZS":  "Account ownership, female 15+. Required for inclusion analysis.",

    # --- Keeps: outcomes ---
    "SL.GDP.PCAP.EM.KD":  "GDP per person employed, constant 2021 PPP. Primary productivity outcome.",
    "SL.TLF.CACT.FE.ZS":  "Female LFP, ages 15+, ILO modelled. Primary participation outcome.",
    "SL.TLF.CACT.FM.ZS":  "Female-to-male LFP ratio, ILO modelled. Secondary participation outcome.",

    # --- Keeps: controls ---
    "NY.GDP.PCAP.PP.KD":  "GDP per capita, constant PPP. Income control.",
    "SE.TER.ENRR":        "Tertiary gross enrolment. Human capital control.",
    "NE.TRD.GNFS.ZS":     "Trade as share of GDP. Openness control.",
    "SP.URB.TOTL.IN.ZS":  "Urban population share. Structural control.",
    "EG.ELC.ACCS.ZS":     "Electricity access, total population. Infrastructure control.",
    "GOV_WGI_GE_EST":     "Government effectiveness, estimate scale. Institutional control.",
    "GOV_WGI_RQ_EST":     "Regulatory quality, estimate scale. Institutional control.",

    # --- Drops: level counts, not normalised ---
    "IT.NET.BBND":        "Level count. Retained rate form for cross-country comparability.",
    "IT.CEL.SETS":        "Level count. Retained rate form for cross-country comparability.",
    "IT.NET.SECR":        "Level count. Retained rate form for cross-country comparability.",
    "BX.GSR.CCIS.CD":     "Nominal USD value. Retained share-of-exports form for comparability.",

    # --- Drops: sub-population splits, out of scope ---
    "FX.OWN.TOTL.40.ZS":  "Income-quintile split. Scope restricted to total and female aggregates.",
    "FX.OWN.TOTL.60.ZS":  "Income-quintile split. Scope restricted to total and female aggregates.",
    "FX.OWN.TOTL.MA.ZS":  "Male-only split. Inclusion analysis uses total and female aggregates.",
    "FX.OWN.TOTL.OL.ZS":  "Age split (25+). Out of scope.",
    "FX.OWN.TOTL.PL.ZS":  "Education split (primary or less). Out of scope.",
    "FX.OWN.TOTL.SO.ZS":  "Education split (secondary or more). Out of scope.",
    "FX.OWN.TOTL.YG.ZS":  "Age split (15-24). Out of scope.",

    # --- Drops: alternative definitions of shortlisted constructs ---
    "SL.TLF.ACTI.FE.ZS":  "Age band 15-64. Retained 15+ headline series for consistency.",
    "SL.TLF.CACT.FE.NE.ZS":"National estimate. Retained ILO modelled series for cross-country comparability.",
    "SL.TLF.CACT.FM.NE.ZS":"National estimate. Retained ILO modelled series for cross-country comparability.",
    "NY.GDP.PCAP.PP.CD":  "Current international prices. Retained constant-price series for real comparisons.",
    "SE.ENR.TERT.FM.ZS":  "Gender parity index. Retained gross enrolment rate.",
    "SE.TER.ENRR.FE":     "Female-only enrolment. Retained total enrolment for control specification.",
    "SE.TER.ENRR.MA":     "Male-only enrolment. Retained total enrolment for control specification.",
    "EG.ELC.ACCS.RU.ZS":  "Rural-only access. Retained total-population access.",
    "EG.ELC.ACCS.UR.ZS":  "Urban-only access. Retained total-population access.",
    "GOV_WGI_GE_SC":      "Rescaled score (0-100). Retained estimate scale for continuity with WGI.",
    "GOV_WGI_RQ_SC":      "Rescaled score (0-100). Retained estimate scale for continuity with WGI.",

    # --- Drops: adjacent but distinct constructs ---
    "TG.VAL.TOTL.GD.ZS":  "Merchandise trade only. Shortlisted measure is total trade share.",

    # --- Drops: keyword collisions on 'urban population' ---
    "EG.CFT.ACCS.UR.ZS":  "Cooking-fuel access, urban. Not an urbanisation measure.",
    "EN.POP.EL5M.UR.ZS":  "Low-elevation population. Not an urbanisation measure.",
    "EN.POP.SLUM.UR.ZS":  "Slum population. Not an urbanisation measure.",
    "EN.URB.LCTY.UR.ZS":  "Largest-city concentration. Not the urban share of total population.",
    "SH.H2O.BASW.UR.ZS":  "Basic drinking water access. Not an urbanisation measure.",
    "SH.H2O.SMDW.UR.ZS":  "Safely managed drinking water. Not an urbanisation measure.",
    "SH.STA.BASS.UR.ZS":  "Basic sanitation access. Not an urbanisation measure.",
    "SH.STA.HYGN.UR.ZS":  "Handwashing facility access. Not an urbanisation measure.",
    "SH.STA.ODFC.UR.ZS":  "Open defecation. Not an urbanisation measure.",
    "SH.STA.SMSS.UR.ZS":  "Safely managed sanitation. Not an urbanisation measure.",
    "SP.URB.GROW":        "Urban population growth rate. Retained urban share of total.",
    "SP.URB.TOTL":        "Urban population level. Retained urban share of total.",
}

decisions["reason"] = decisions["code"].map(reasons)
print(decisions["reason"].isna().sum(), "rows without a reason")
print(decisions.shape)
print(decisions["decision"].value_counts())
decisions.to_csv("shortlist_decisions.csv", index=False)
print(decisions.head(20).to_string())

0 rows without a reason
(56, 5)
decision
drop    36
keep    20
Name: count, dtype: int64
                                         keyword               code                                                                                                                                          name decision                                                                    reason
0                 Individuals using the Internet  IT.NET.USER.FE.ZS                                                                               Individuals using the Internet, female (% of female population)     keep        Female internet penetration. Required to construct the gender gap.
1                 Individuals using the Internet  IT.NET.USER.MA.ZS                                                                                   Individuals using the Internet, male (% of male population)     keep          Male internet penetration. Required to construct the gender gap.
2                 Individuals using the Internet     IT.NET.USER.ZS                                                                                              Individuals using the Internet (% of population)     keep             Total internet penetration. Primary digital adoption measure.
3                  Fixed broadband subscriptions        IT.NET.BBND                                                                                                                 Fixed broadband subscriptions     drop          Level count. Retained rate form for cross-country comparability.
4                  Fixed broadband subscriptions     IT.NET.BBND.P2                                                                                                Fixed broadband subscriptions (per 100 people)     keep       Fixed broadband per 100. Rate form for cross-country comparability.
5                  Mobile cellular subscriptions        IT.CEL.SETS                                                                                                                 Mobile cellular subscriptions     drop          Level count. Retained rate form for cross-country comparability.
6                  Mobile cellular subscriptions     IT.CEL.SETS.P2                                                                                                Mobile cellular subscriptions (per 100 people)     keep  Mobile subscriptions per 100. Rate form for cross-country comparability.
7                        Secure Internet servers        IT.NET.SECR                                                                                                                       Secure Internet servers     drop          Level count. Retained rate form for cross-country comparability.
8                        Secure Internet servers     IT.NET.SECR.P6                                                                                                Secure Internet servers (per 1 million people)     keep         Secure servers per 1m. Rate form for cross-country comparability.
9                            ICT service exports     BX.GSR.CCIS.CD                                                                                                        ICT service exports (BoP, current US$)     drop      Nominal USD value. Retained share-of-exports form for comparability.
10                           ICT service exports     BX.GSR.CCIS.ZS                                                                                               ICT service exports (% of service exports, BoP)     keep  ICT service exports as share of service exports. Scale-free, comparable.
11  Investment in ICT with private participation     IE.PPI.ICTI.CD                                                                                    Investment in ICT with private participation (current US$)     keep        ICT investment with private participation. Only available variant.
12  Account ownership at a financial institution  FX.OWN.TOTL.40.ZS                  Account ownership at a financial institution or with a mobile-money-service provider, poorest 40% (% of population ages 15+)     drop   Income-quintile split. Scope restricted to total and female aggregates.
13  Account ownership at a financial institution  FX.OWN.TOTL.60.ZS                  Account ownership at a financial institution or with a mobile-money-service provider, richest 60% (% of population ages 15+)     drop   Income-quintile split. Scope restricted to total and female aggregates.
14  Account ownership at a financial institution  FX.OWN.TOTL.FE.ZS                       Account ownership at a financial institution or with a mobile-money-service provider, female (% of population ages 15+)     keep           Account ownership, female 15+. Required for inclusion analysis.
15  Account ownership at a financial institution  FX.OWN.TOTL.MA.ZS                         Account ownership at a financial institution or with a mobile-money-service provider, male (% of population ages 15+)     drop     Male-only split. Inclusion analysis uses total and female aggregates.
16  Account ownership at a financial institution  FX.OWN.TOTL.OL.ZS                 Account ownership at a financial institution or with a mobile-money-service provider, older adults (% of population ages 25+)     drop                                            Age split (25+). Out of scope.
17  Account ownership at a financial institution  FX.OWN.TOTL.PL.ZS    Account ownership at a financial institution or with a mobile-money-service provider, primary education or less (% of population ages 15+)     drop                          Education split (primary or less). Out of scope.
18  Account ownership at a financial institution  FX.OWN.TOTL.SO.ZS  Account ownership at a financial institution or with a mobile-money-service provider, secondary education or more (% of population ages 15+)     drop                        Education split (secondary or more). Out of scope.
19  Account ownership at a financial institution  FX.OWN.TOTL.YG.ZS               Account ownership at a financial institution or with a mobile-money-service provider, young adults (% of population ages 15-24)     drop                                          Age split (15-24). Out of scope.

In [29]:
import pandas as pd
w = pd.read_csv("panel_window_2011_2024.csv")
print(w.shape)
print(w.columns.tolist())
print(w.head())
print(w.groupby("country").size().describe())

(876, 14)
['country', 'year', 'EG.ELC.ACCS.ZS', 'GOV_WGI_GE_EST', 'GOV_WGI_RQ_EST', 'IT.NET.USER.FE.ZS', 'IT.NET.USER.MA.ZS', 'IT.NET.USER.ZS', 'NE.TRD.GNFS.ZS', 'NY.GDP.PCAP.PP.KD', 'SE.TER.ENRR', 'SL.GDP.PCAP.EM.KD', 'SL.TLF.CACT.FE.ZS', 'SP.URB.TOTL.IN.ZS']
  country  year  EG.ELC.ACCS.ZS  GOV_WGI_GE_EST  GOV_WGI_RQ_EST  \
0     ALB  2019           100.0        0.115817        0.163741
1     ALB  2020           100.0       -0.009337        0.059186
2     ALB  2021           100.0        0.108063        0.056966
3     ALB  2022           100.0        0.192283        0.059804
4     ALB  2023           100.0        0.264196        0.104090

   IT.NET.USER.FE.ZS  IT.NET.USER.MA.ZS  IT.NET.USER.ZS  NE.TRD.GNFS.ZS  \
0            65.9616            71.1594       68.550391       75.382129
1            71.2457            73.2383       72.237677       59.520699
2            78.3496            80.3109       79.323718       75.590404
3            81.5432            83.7135       82.613675       84.698044
4            81.7239            84.5900       83.135592       82.352493

   NY.GDP.PCAP.PP.KD  SE.TER.ENRR  SL.GDP.PCAP.EM.KD  SL.TLF.CACT.FE.ZS  \
0       16761.123018    61.408514       38164.614850             52.931
1       16457.718974    61.585302       38038.149906             52.252
2       18212.794718    59.969869       41715.292582             52.523
3       19388.792728    62.647922       42235.933353             56.407
4       20501.647073    64.729352       43306.514661             57.963

   SP.URB.TOTL.IN.ZS
0          56.763907
1          57.140859
2          57.507719
3          57.864348
4          58.210609
count    107.000000
mean       8.186916
std        4.686655
min        1.000000
25%        3.500000
50%        9.000000
75%       13.000000
max       14.000000
dtype: float64

In [30]:
years_per_country = w.groupby("country").size()

print("Countries with 1 year:", (years_per_country == 1).sum())
print("Countries with 2-3 years:", ((years_per_country >= 2) & (years_per_country <= 3)).sum())
print("Countries with 4-7 years:", ((years_per_country >= 4) & (years_per_country <= 7)).sum())
print("Countries with 8+ years:", (years_per_country >= 8).sum())
print()
print("Total countries:", len(years_per_country))

Countries with 1 year: 13
Countries with 2-3 years: 14
Countries with 4-7 years: 15
Countries with 8+ years: 65

Total countries: 107

In [31]:
years_per_country = w.groupby("country").size()
keep_countries = years_per_country[years_per_country >= 3].index

w_filtered = w[w["country"].isin(keep_countries)].copy()
w_filtered = w_filtered.sort_values(["country", "year"])

print("Countries kept:", w_filtered["country"].nunique())
print("Rows kept:", len(w_filtered))
print("Years per country after filter:")
print(w_filtered.groupby("country").size().describe())

Countries kept: 86
Rows kept: 847
Years per country after filter:
count    86.000000
mean      9.848837
std       3.618636
min       3.000000
25%       8.000000
50%      10.000000
75%      13.000000
max      14.000000
dtype: float64

In [32]:
# gender gap
w_filtered["gender_gap"] = (
    w_filtered["IT.NET.USER.MA.ZS"] - w_filtered["IT.NET.USER.FE.ZS"]
)

# lagged digital adoption within country
w_filtered = w_filtered.sort_values(["country", "year"]).copy()
w_filtered["IT_lag1"] = (
    w_filtered.groupby("country")["IT.NET.USER.ZS"].shift(1)
)

# report what we have
print("Rows before lag drop:", len(w_filtered))
print("Rows with non-null lag:", w_filtered["IT_lag1"].notna().sum())
print()
print("Gender gap summary:")
print(w_filtered["gender_gap"].describe())
print()
print(w_filtered[["country", "year", "IT.NET.USER.ZS", "IT_lag1",
                  "IT.NET.USER.MA.ZS", "IT.NET.USER.FE.ZS", "gender_gap"]].head(10))

Rows before lag drop: 847
Rows with non-null lag: 761

Gender gap summary:
count    847.000000
mean       2.786897
std        3.936985
min      -20.010900
25%        0.370200
50%        2.058900
75%        4.351700
max       33.803800
Name: gender_gap, dtype: float64

  country  year  IT.NET.USER.ZS     IT_lag1  IT.NET.USER.MA.ZS  \
0     ALB  2019       68.550391         NaN            71.1594
1     ALB  2020       72.237677   68.550391            73.2383
2     ALB  2021       79.323718   72.237677            80.3109
3     ALB  2022       82.613675   79.323718            83.7135
4     ALB  2023       83.135592   82.613675            84.5900
5     ARE  2018       98.450002         NaN            98.3353
6     ARE  2019       99.149998   98.450002            99.0300
7     ARE  2020      100.000000   99.149998           100.0000
8     ARE  2021      100.000000  100.000000           100.0000
9     ARE  2022      100.000000  100.000000           100.0000

   IT.NET.USER.FE.ZS  gender_gap
0            65.9616      5.1978
1            71.2457      1.9926
2            78.3496      1.9613
3            81.5432      2.1703
4            81.7239      2.8661
5            98.8000     -0.4647
6            99.5015     -0.4715
7           100.0000      0.0000
8           100.0000      0.0000
9           100.0000      0.0000

In [33]:
w_filtered.to_csv("panel_task2.csv", index=False)

# inspect tails of gender gap
print("Most negative gender gaps (women ahead):")
print(w_filtered.nsmallest(5, "gender_gap")[
    ["country", "year", "IT.NET.USER.MA.ZS", "IT.NET.USER.FE.ZS", "gender_gap"]
])

print()
print("Most positive gender gaps (men ahead):")
print(w_filtered.nlargest(5, "gender_gap")[
    ["country", "year", "IT.NET.USER.MA.ZS", "IT.NET.USER.FE.ZS", "gender_gap"]
])

# how many rows are at the 100% ceiling
print()
print("Rows where total internet use is 100:", (w_filtered["IT.NET.USER.ZS"] == 100).sum())

Most negative gender gaps (women ahead):
    country  year  IT.NET.USER.MA.ZS  IT.NET.USER.FE.ZS  gender_gap
85      BHR  2011            70.0000            90.0109    -20.0109
606     MNG  2018            42.7963            51.2040     -8.4077
607     MNG  2019            46.8610            55.0473     -8.1863
128     BRA  2020            77.3330            84.9105     -7.5775
87      BHR  2014            87.9999            95.0001     -7.0002

Most positive gender gaps (men ahead):
    country  year  IT.NET.USER.MA.ZS  IT.NET.USER.FE.ZS  gender_gap
156     CIV  2017            60.2019            26.3981     33.8038
832     TUR  2012            55.8033            34.6829     21.1204
833     TUR  2013            56.6006            36.0678     20.5328
549     MAR  2012            65.3959            45.7717     19.6242
835     TUR  2015            63.5388            44.0396     19.4992

Rows where total internet use is 100: 11

In [34]:
pip install linearmodels

Collecting linearmodels
  Downloading linearmodels-7.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (10 kB)
Requirement already satisfied: numpy<3,>=1.22.3 in /opt/anaconda3/lib/python3.13/site-packages (from linearmodels) (2.3.5)
Requirement already satisfied: pandas>=1.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from linearmodels) (2.3.3)
Requirement already satisfied: scipy>=1.8.0 in /opt/anaconda3/lib/python3.13/site-packages (from linearmodels) (1.16.3)
Requirement already satisfied: statsmodels>=0.13.0 in /opt/anaconda3/lib/python3.13/site-packages (from linearmodels) (0.14.5)
Requirement already satisfied: mypy_extensions>=0.4 in /opt/anaconda3/lib/python3.13/site-packages (from linearmodels) (1.0.0)
Collecting pyhdfe>=0.1 (from linearmodels)
  Downloading pyhdfe-0.2.0-py3-none-any.whl.metadata (4.0 kB)
Collecting formulaic>=1.2.1 (from linearmodels)
  Downloading formulaic-1.2.2-py3-none-any.whl.metadata (7.0 kB)
Collecting interface-meta>=1.2.0 (from formulaic>=1.2.1->linearmodels)
  Downloading interface_meta-2.0.1-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: narwhals>=1.17 in /opt/anaconda3/lib/python3.13/site-packages (from formulaic>=1.2.1->linearmodels) (2.7.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from formulaic>=1.2.1->linearmodels) (4.15.0)
Requirement already satisfied: wrapt>=1.17.0rc1 in /opt/anaconda3/lib/python3.13/site-packages (from formulaic>=1.2.1->linearmodels) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.4.0->linearmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.4.0->linearmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.4.0->linearmodels) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.4.0->linearmodels) (1.17.0)
Requirement already satisfied: patsy>=0.5.6 in /opt/anaconda3/lib/python3.13/site-packages (from statsmodels>=0.13.0->linearmodels) (1.0.1)
Requirement already satisfied: packaging>=21.3 in /opt/anaconda3/lib/python3.13/site-packages (from statsmodels>=0.13.0->linearmodels) (25.0)
Downloading linearmodels-7.0-cp313-cp313-macosx_11_0_arm64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 1.6 MB/s  0:00:00m 5.5 MB/s eta 0:00:01
Downloading formulaic-1.2.2-py3-none-any.whl (118 kB)
Downloading interface_meta-2.0.1-py3-none-any.whl (15 kB)
Downloading pyhdfe-0.2.0-py3-none-any.whl (19 kB)
Installing collected packages: interface-meta, pyhdfe, formulaic, linearmodels
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [linearmodels]0m 3/4 [linearmodels]
Successfully installed formulaic-1.2.2 interface-meta-2.0.1 linearmodels-7.0 pyhdfe-0.2.0
Note: you may need to restart the kernel to use updated packages.

In [3]:
from linearmodels.panel import PanelOLS

df = pd.read_csv("panel_task2.csv")
df = df.dropna(subset=["IT_lag1"])
df = df.set_index(["country", "year"])

outcome = "SL.GDP.PCAP.EM.KD"
#GDP per person employed, constant 2021 PPP dollars.
regressors = [
    "IT_lag1",
    "NY.GDP.PCAP.PP.KD",
    "SE.TER.ENRR",
    "NE.TRD.GNFS.ZS",
    "SP.URB.TOTL.IN.ZS",
    "EG.ELC.ACCS.ZS",
    "GOV_WGI_GE_EST",
    "GOV_WGI_RQ_EST",
]
#IT_lag1 — internet penetration, lagged one year, as a percentage of the population. Calculated above
#NY.GDP.PCAP.PP.KD — GDP per capita, constant 2021 PPP dollars.
#SE.TER.ENRR — tertiary school enrolment, gross percentage
#NE.TRD.GNFS.ZS — trade as a percentage of GDP.
#SP.URB.TOTL.IN.ZS — urban population as a percentage of total population.
#EG.ELC.ACCS.ZS — access to electricity, percentage of population.
#GOV_WGI_GE_EST — government effectiveness, WGI estimate scale (roughly -2.5 to +2.5)
#GOV_WGI_RQ_EST — regulatory quality, WGI estimate scale (roughly -2.5 to +2.5)
y = df[outcome]
X = df[regressors]

mod = PanelOLS(y, X, entity_effects=True, time_effects=True)
res = mod.fit(cov_type="clustered", cluster_entity=True)

print(res.summary)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:      SL.GDP.PCAP.EM.KD   R-squared:                        0.8958
Estimator:                   PanelOLS   R-squared (Between):              0.9210
No. Observations:                 761   R-squared (Within):               0.8849
Date:                Tue, Oct 13 2026   R-squared (Overall):              0.9354
Time:                        11:46:22   Log-likelihood                   -6956.2
Cov. Estimator:             Clustered
                                        F-statistic:                      703.84
Entities:                          86   P-value                           0.0000
Avg Obs:                       8.8488   Distribution:                   F(8,655)
Min Obs:                       2.0000
Max Obs:                       13.000   F-statistic (robust):             177.41
                                        P-value                           0.0000
Time periods:                      13   Distribution:                   F(8,655)
Avg Obs:                       58.538
Min Obs:                       36.000
Max Obs:                       75.000

                                 Parameter Estimates
=====================================================================================
                   Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-------------------------------------------------------------------------------------
IT_lag1               55.639     33.291     1.6713     0.0951     -9.7317      121.01
NY.GDP.PCAP.PP.KD     1.5794     0.0552     28.627     0.0000      1.4711      1.6878
SE.TER.ENRR           7.1634     51.504     0.1391     0.8894     -93.969      108.30
NE.TRD.GNFS.ZS       -45.205     26.377    -1.7138     0.0870     -96.999      6.5886
SP.URB.TOTL.IN.ZS     159.24     171.68     0.9275     0.3540     -177.87      496.34
EG.ELC.ACCS.ZS        313.45     177.04     1.7706     0.0771     -34.174      661.08
GOV_WGI_GE_EST        1669.9     3015.2     0.5538     0.5799     -4250.7      7590.5
GOV_WGI_RQ_EST       -2325.9     2044.5    -1.1376     0.2557     -6340.5      1688.7
=====================================================================================

F-test for Poolability: 244.57
P-value: 0.0000
Distribution: F(97,655)

Included effects: Entity, Time

In [4]:
with open("results_productivity.txt", "w") as f:
    f.write(str(res.summary))

In [5]:
outcome = "SL.TLF.CACT.FE.ZS"
# outcome is Labor force participation rate, female, ages 15+, modeled ILO estimate.
y = df[outcome]
X = df[regressors]

mod_lfp = PanelOLS(y, X, entity_effects=True, time_effects=True)
res_lfp = mod_lfp.fit(cov_type="clustered", cluster_entity=True)

print(res_lfp.summary)

with open("results_flfp.txt", "w") as f:
    f.write(str(res_lfp.summary))

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:      SL.TLF.CACT.FE.ZS   R-squared:                        0.0534
Estimator:                   PanelOLS   R-squared (Between):             -1.4484
No. Observations:                 761   R-squared (Within):               0.0230
Date:                Tue, Oct 13 2026   R-squared (Overall):             -1.4589
Time:                        11:55:13   Log-likelihood                   -1346.7
Cov. Estimator:             Clustered
                                        F-statistic:                      4.6202
Entities:                          86   P-value                           0.0000
Avg Obs:                       8.8488   Distribution:                   F(8,655)
Min Obs:                       2.0000
Max Obs:                       13.000   F-statistic (robust):             1.0582
                                        P-value                           0.3908
Time periods:                      13   Distribution:                   F(8,655)
Avg Obs:                       58.538
Min Obs:                       36.000
Max Obs:                       75.000

                                 Parameter Estimates
=====================================================================================
                   Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-------------------------------------------------------------------------------------
IT_lag1              -0.0175     0.0215    -0.8172     0.4141     -0.0597      0.0246
NY.GDP.PCAP.PP.KD  4.032e-05  3.194e-05     1.2624     0.2073   -2.24e-05      0.0001
SE.TER.ENRR           0.0109     0.0190     0.5725     0.5672     -0.0265      0.0483
NE.TRD.GNFS.ZS        0.0123     0.0140     0.8786     0.3799     -0.0151      0.0397
SP.URB.TOTL.IN.ZS    -0.1008     0.0993    -1.0149     0.3105     -0.2958      0.0942
EG.ELC.ACCS.ZS       -0.2511     0.1650    -1.5216     0.1286     -0.5752      0.0729
GOV_WGI_GE_EST        0.5772     0.9346     0.6175     0.5371     -1.2581      2.4124
GOV_WGI_RQ_EST       -0.6298     1.4689    -0.4287     0.6682     -3.5142      2.2546
=====================================================================================

F-test for Poolability: 243.49
P-value: 0.0000
Distribution: F(97,655)

Included effects: Entity, Time

In [6]:
with open("results_flfp.txt", "w") as f:
    f.write(str(res_lfp.summary))

In [8]:
df["IT_lag1_x_gap"] = df["IT_lag1"] * df["gender_gap"]

interaction_regs = [
    "IT_lag1",
    "gender_gap",
    "IT_lag1_x_gap",
    "NY.GDP.PCAP.PP.KD",
    "SE.TER.ENRR",
    "NE.TRD.GNFS.ZS",
    "SP.URB.TOTL.IN.ZS",
    "EG.ELC.ACCS.ZS",
    "GOV_WGI_GE_EST",
    "GOV_WGI_RQ_EST",
]

y = df["SL.TLF.CACT.FE.ZS"]
X = df[interaction_regs]

mod_int = PanelOLS(y, X, entity_effects=True, time_effects=True)
res_int = mod_int.fit(cov_type="clustered", cluster_entity=True)

print(res_int.summary)

with open("results_interaction.txt", "w") as f:
    f.write(str(res_int.summary))

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:      SL.TLF.CACT.FE.ZS   R-squared:                        0.0638
Estimator:                   PanelOLS   R-squared (Between):             -1.3250
No. Observations:                 761   R-squared (Within):               0.0740
Date:                Tue, Oct 13 2026   R-squared (Overall):             -1.3335
Time:                        11:58:26   Log-likelihood                   -1342.5
Cov. Estimator:             Clustered
                                        F-statistic:                      4.4464
Entities:                          86   P-value                           0.0000
Avg Obs:                       8.8488   Distribution:                  F(10,653)
Min Obs:                       2.0000
Max Obs:                       13.000   F-statistic (robust):             0.9527
                                        P-value                           0.4839
Time periods:                      13   Distribution:                  F(10,653)
Avg Obs:                       58.538
Min Obs:                       36.000
Max Obs:                       75.000

                                 Parameter Estimates
=====================================================================================
                   Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-------------------------------------------------------------------------------------
IT_lag1              -0.0119     0.0277    -0.4307     0.6668     -0.0664      0.0425
gender_gap            0.0633     0.2307     0.2742     0.7840     -0.3898      0.5163
IT_lag1_x_gap        -0.0021     0.0035    -0.5873     0.5572     -0.0090      0.0049
NY.GDP.PCAP.PP.KD   3.91e-05  3.105e-05     1.2594     0.2083  -2.187e-05      0.0001
SE.TER.ENRR           0.0105     0.0196     0.5362     0.5920     -0.0280      0.0490
NE.TRD.GNFS.ZS        0.0108     0.0141     0.7699     0.4416     -0.0168      0.0384
SP.URB.TOTL.IN.ZS    -0.0853     0.1011    -0.8437     0.3991     -0.2838      0.1132
EG.ELC.ACCS.ZS       -0.2420     0.1683    -1.4381     0.1509     -0.5724      0.0884
GOV_WGI_GE_EST        0.5780     0.9028     0.6402     0.5223     -1.1948      2.3508
GOV_WGI_RQ_EST       -0.5372     1.4740    -0.3645     0.7156     -3.4315      2.3571
=====================================================================================

F-test for Poolability: 203.53
P-value: 0.0000
Distribution: F(97,653)

Included effects: Entity, Time

In [11]:



df = pd.read_csv("panel_task2.csv")
df = df.dropna(subset=["IT_lag1"])
df = df.set_index(["country", "year"])

regressors = [
    "IT_lag1",
    "NY.GDP.PCAP.PP.KD",
    "SE.TER.ENRR",
    "NE.TRD.GNFS.ZS",
    "SP.URB.TOTL.IN.ZS",
    "EG.ELC.ACCS.ZS",
    "GOV_WGI_GE_EST",
    "GOV_WGI_RQ_EST",
]

results = []

for outcome in ["SL.GDP.PCAP.EM.KD", "SL.TLF.CACT.FE.ZS"]:
    y = df[outcome]
    X = df[regressors]

    pooled = PooledOLS(y, X).fit(cov_type="clustered", cluster_entity=True)
    results.append({
        "outcome": outcome, "spec": "pooled",
        "coef": pooled.params["IT_lag1"],
        "se": pooled.std_errors["IT_lag1"],
        "pval": pooled.pvalues["IT_lag1"],
    })

    fe = PanelOLS(y, X, entity_effects=True, time_effects=True).fit(
        cov_type="clustered", cluster_entity=True
    )
    results.append({
        "outcome": outcome, "spec": "fe",
        "coef": fe.params["IT_lag1"],
        "se": fe.std_errors["IT_lag1"],
        "pval": fe.pvalues["IT_lag1"],
    })

out = pd.DataFrame(results)
out.to_csv("python_coef_table.csv", index=False)
print(out.to_string(index=False))

          outcome   spec       coef        se     pval
SL.GDP.PCAP.EM.KD pooled -57.617001 69.878894 0.409902
SL.GDP.PCAP.EM.KD     fe  55.638554 33.291138 0.095146
SL.TLF.CACT.FE.ZS pooled   0.058937  0.063654 0.354790
SL.TLF.CACT.FE.ZS     fe  -0.017538  0.021462 0.414137

In [12]:
import os
print(os.path.exists("python_coef_table.csv"))

True

In [16]:


python = pd.read_csv("python_coef_table.csv")
print("Python:")
print(python.to_string(index=False))

print()
for f in ["r_results_productivity.txt", "r_results_flfp.txt", "r_results_interaction.txt"]:
    print(f"R: {f}")
    with open(f) as fh:
        print(fh.read())
    print("---")

Python:
          outcome   spec       coef        se     pval
SL.GDP.PCAP.EM.KD pooled -57.617001 69.878894 0.409902
SL.GDP.PCAP.EM.KD     fe  55.638554 33.291138 0.095146
SL.TLF.CACT.FE.ZS pooled   0.058937  0.063654 0.354790
SL.TLF.CACT.FE.ZS     fe  -0.017538  0.021462 0.414137

R: r_results_productivity.txt
                              m_prod
Dependent Var.:    SL.GDP.PCAP.EM.KD

IT_lag1               55.64. (31.48)
NY.GDP.PCAP.PP.KD  1.579*** (0.0522)
SE.TER.ENRR            7.163 (48.71)
NE.TRD.GNFS.ZS       -45.20. (24.94)
SP.URB.TOTL.IN.ZS      159.2 (162.4)
EG.ELC.ACCS.ZS        313.5. (167.4)
GOV_WGI_GE_EST     1,669.9 (2,851.5)
GOV_WGI_RQ_EST    -2,325.9 (1,933.5)
Fixed-Effects:    ------------------
country                          Yes
year                             Yes
_________________ __________________
S.E.: Clustered          by: country
Observations                     761
R2                           0.99781
Within R2                    0.89580
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

---
R: r_results_flfp.txt
                              m_lfp
Dependent Var.:   SL.TLF.CACT.FE.ZS

IT_lag1            -0.0175 (0.0203)
NY.GDP.PCAP.PP.KD 4.03e-5 (3.02e-5)
SE.TER.ENRR         0.0109 (0.0180)
NE.TRD.GNFS.ZS      0.0123 (0.0132)
SP.URB.TOTL.IN.ZS  -0.1008 (0.0939)
EG.ELC.ACCS.ZS     -0.2511 (0.1561)
GOV_WGI_GE_EST      0.5772 (0.8839)
GOV_WGI_RQ_EST      -0.6298 (1.389)
Fixed-Effects:    -----------------
country                         Yes
year                            Yes
_________________ _________________
S.E.: Clustered         by: country
Observations                    761
R2                          0.98053
Within R2                   0.05341
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

---
R: r_results_interaction.txt
                              m_int
Dependent Var.:   SL.TLF.CACT.FE.ZS

IT_lag1            -0.0119 (0.0262)
gender_gap          0.0633 (0.2181)
IT_lag1_x_gap      -0.0021 (0.0033)
NY.GDP.PCAP.PP.KD 3.91e-5 (2.94e-5)
SE.TER.ENRR         0.0105 (0.0185)
NE.TRD.GNFS.ZS      0.0108 (0.0133)
SP.URB.TOTL.IN.ZS  -0.0853 (0.0956)
EG.ELC.ACCS.ZS     -0.2420 (0.1591)
GOV_WGI_GE_EST      0.5780 (0.8537)
GOV_WGI_RQ_EST      -0.5372 (1.394)
Fixed-Effects:    -----------------
country                         Yes
year                            Yes
_________________ _________________
S.E.: Clustered         by: country
Observations                    761
R2                          0.98074
Within R2                   0.06375
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

---

In [17]:
stata = pd.read_csv("stata_coef_table.txt", sep="\t", skiprows=1, on_bad_lines="skip", engine="python")
print(stata.to_string())

                               Unnamed: 0         m_prod          m_lfp          m_int
0                               VARIABLES  slgdppcapemkd  sltlfcactfezs  sltlfcactfezs
1                                     NaN            NaN            NaN            NaN
2                                 it_lag1         55.64*        -0.0175        -0.0119
3                                     NaN        (31.48)       (0.0203)       (0.0262)
4                              gender_gap            NaN            NaN         0.0633
5                                     NaN            NaN            NaN        (0.218)
6                           it_lag1_x_gap            NaN            NaN       -0.00208
7                                     NaN            NaN            NaN      (0.00335)
8                           nygdppcapppkd       1.579***       4.03e-05       3.91e-05
9                                     NaN       (0.0522)     (3.02e-05)     (2.94e-05)
10                              seterenrr          7.163         0.0109         0.0105
11                                    NaN        (48.71)       (0.0180)       (0.0185)
12                            netrdgnfszs        -45.20*         0.0123         0.0108
13                                    NaN        (24.94)       (0.0132)       (0.0133)
14                          spurbtotlinzs          159.2         -0.101        -0.0853
15                                    NaN        (162.4)       (0.0939)       (0.0956)
16                            egelcaccszs         313.5*         -0.251         -0.242
17                                    NaN        (167.4)        (0.156)        (0.159)
18                         gov_wgi_ge_est          1,670          0.577          0.578
19                                    NaN        (2,851)        (0.884)        (0.854)
20                         gov_wgi_rq_est         -2,326         -0.630         -0.537
21                                    NaN        (1,934)        (1.389)        (1.394)
22                               Constant        -20,287       81.05***       78.94***
23                                    NaN       (22,900)        (17.31)        (17.25)
24                                    NaN            NaN            NaN            NaN
25                           Observations            761            761            761
26                              R-squared          0.998          0.981          0.981
27  Robust standard errors in parentheses            NaN            NaN            NaN
28         *** p<0.01, ** p<0.05, * p<0.1            NaN            NaN            NaN

In [19]:
import re
stata = pd.read_csv("stata_coef_table.txt", sep="\t", header=0, engine="python", skipinitialspace=True)
stata.columns = ["var", "m_prod", "m_lfp", "m_int"]

def grab(var_name, col):
    row = stata[stata["var"] == var_name]
    if row.empty:
        return None, None
    coef_str = str(row[col].values[0])
    idx = row.index[0]
    se_str = str(stata.iloc[idx + 1][col]) if idx + 1 < len(stata) else ""
    coef = float(re.sub(r"[^\d\.\-]", "", coef_str.split("(")[0].strip()) or "nan")
    se_match = re.search(r"\(([^)]+)\)", se_str)
    se = float(re.sub(r"[^\d\.\-]", "", se_match.group(1))) if se_match else None
    return coef, se

rows = [
    {"outcome": "SL.GDP.PCAP.EM.KD", "spec": "fe",             "term": "it_lag1",       "stata_coef": grab("it_lag1", "m_prod")[0],       "stata_se": grab("it_lag1", "m_prod")[1]},
    {"outcome": "SL.TLF.CACT.FE.ZS", "spec": "fe",             "term": "it_lag1",       "stata_coef": grab("it_lag1", "m_lfp")[0],        "stata_se": grab("it_lag1", "m_lfp")[1]},
    {"outcome": "SL.TLF.CACT.FE.ZS", "spec": "fe_interaction", "term": "it_lag1_x_gap", "stata_coef": grab("it_lag1_x_gap", "m_int")[0],  "stata_se": grab("it_lag1_x_gap", "m_int")[1]},
]

s = pd.DataFrame(rows)
print(s.to_string(index=False))
s.to_csv("stata_coef_table_clean.csv", index=False)

          outcome           spec          term  stata_coef  stata_se
SL.GDP.PCAP.EM.KD             fe       it_lag1    55.64000  31.48000
SL.TLF.CACT.FE.ZS             fe       it_lag1    -0.01750   0.02030
SL.TLF.CACT.FE.ZS fe_interaction it_lag1_x_gap    -0.00208   0.00335

In [21]:


def parse_r_line(line):
    # line looks like "IT_lag1               55.64. (31.48)"
    parts = line.strip().split()
    # parts[0] = "IT_lag1", parts[1] = "55.64.", parts[2] = "(31.48)"
    coef_raw = parts[1]
    # strip anything that is not a digit, minus, or dot
    coef_clean = re.sub(r"[^\d\.\-]", "", coef_raw)
    # remove trailing dots
    coef_clean = coef_clean.rstrip(".")
    coef = float(coef_clean)
    se_match = re.search(r"\(([^)]+)\)", line)
    se = float(se_match.group(1)) if se_match else None
    return coef, se

def read_r_coef(path, term, outcome, spec):
    with open(path) as f:
        for line in f:
            stripped = line.strip()
            if stripped.startswith(term):
                coef, se = parse_r_line(stripped)
                return {"outcome": outcome, "spec": spec, "term": term,
                        "r_coef": coef, "r_se": se}
    return None

r_rows = [
    read_r_coef("r_results_productivity.txt", "IT_lag1", "SL.GDP.PCAP.EM.KD", "fe"),
    read_r_coef("r_results_flfp.txt", "IT_lag1", "SL.TLF.CACT.FE.ZS", "fe"),
    read_r_coef("r_results_interaction.txt", "IT_lag1_x_gap", "SL.TLF.CACT.FE.ZS", "fe_interaction"),
]
r = pd.DataFrame(r_rows)
print(r.to_string(index=False))

          outcome           spec          term  r_coef    r_se
SL.GDP.PCAP.EM.KD             fe       IT_lag1 55.6400 31.4800
SL.TLF.CACT.FE.ZS             fe       IT_lag1 -0.0175  0.0203
SL.TLF.CACT.FE.ZS fe_interaction IT_lag1_x_gap -0.0021  0.0033

In [23]:
import pandas as pd

# --- Python ---
python = pd.read_csv("python_coef_table.csv")

py_fe = python[python["spec"] == "fe"][["outcome", "coef", "se"]].copy()
py_fe["spec"] = "fe"
py_fe["term"] = "IT_lag1"
py_fe = py_fe.rename(columns={"coef": "py_coef", "se": "py_se"})

py_int = pd.DataFrame([{
    "outcome": "SL.TLF.CACT.FE.ZS", "spec": "fe_interaction",
    "term": "IT_lag1_x_gap", "py_coef": -0.0021, "py_se": 0.0035,
}])
py = pd.concat([py_fe, py_int], ignore_index=True)

# --- R (already parsed in previous cell as r) ---
# --- Stata ---
s = pd.read_csv("stata_coef_table_clean.csv")
s = s.rename(columns={"stata_coef": "stata_coef", "stata_se": "stata_se"})

# --- Merge ---
out = py.merge(r[["outcome", "spec", "r_coef", "r_se"]], on=["outcome", "spec"], how="left")
out = out.merge(s[["outcome", "spec", "stata_coef", "stata_se"]], on=["outcome", "spec"], how="left")

out = out[["outcome", "spec", "term",
           "py_coef", "r_coef", "stata_coef",
           "py_se", "r_se", "stata_se"]]

out.to_csv("task3_reconciliation.csv", index=False)
print(out.to_string(index=False))

          outcome           spec          term   py_coef  r_coef  stata_coef     py_se    r_se  stata_se
SL.GDP.PCAP.EM.KD             fe       IT_lag1 55.638554 55.6400    55.64000 33.291138 31.4800  31.48000
SL.TLF.CACT.FE.ZS             fe       IT_lag1 -0.017538 -0.0175    -0.01750  0.021462  0.0203   0.02030
SL.TLF.CACT.FE.ZS fe_interaction IT_lag1_x_gap -0.002100 -0.0021    -0.00208  0.003500  0.0033   0.00335