In [2]:
import numpy as np,pandas as pd

In [9]:
# reading 2024 person file.
person_2024= pd.read_csv("/Users/abhishek/Desktop/world-bank-indicators-project/PLFS_2024/cperv1.csv")

In [10]:
person_2024.head(200)

,Panel,File_Identification,Schedule,Quarter,Visit,Sector,State_UT_Code,District_Code,NSS_Region,Stratum,...,Day1_Additional_Work_Hours,CWS_Status_Code,CWS_Industry_Code,CWS_Occupation_Code,CWS_Earnings_Salaried,CWS_Earnings_SelfEmployed,Ns_Count_Sector_Stratum_Substratum_Subsample,Ns_Count_Sector_Stratum_Substratum,Subsample_Multiplier,State_Sector_Stratum_Substra
0,P4,CFVP4,104,Q3,V1,1,28,20,281,1,...,0,31,84.0,335.0,9500,0,1,2,1204376,4
1,P4,CFVP4,104,Q3,V1,1,28,20,281,1,...,0,21,1.0,611.0,0,0,1,2,1204376,4
2,P4,CFVP4,104,Q3,V1,1,28,20,281,1,...,0,11,1.0,611.0,0,16500,1,2,1204376,4
3,P4,CFVP4,104,Q3,V1,1,28,20,281,1,...,0,31,86.0,531.0,11500,0,1,2,1204376,4
4,P4,CFVP4,104,Q3,V1,1,28,20,281,1,...,0,91,NaN,NaN,0,0,1,2,1204376,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,P4,CFVP4,104,Q3,V1,1,28,1,281,1,...,0,99,NaN,NaN,0,0,1,2,2632117,4
196,P4,CFVP4,104,Q3,V1,1,28,1,281,1,...,0,92,NaN,NaN,0,0,1,2,2632117,4
197,P4,CFVP4,104,Q3,V1,1,28,1,281,1,...,0,99,NaN,NaN,0,0,1,2,2632117,4
198,P4,CFVP4,104,Q3,V1,1,28,1,281,1,...,0,11,1.0,611.0,0,10000,1,2,1495521,4
199,P4,CFVP4,104,Q3,V1,1,28,1,281,1,...,0,51,41.0,931.0,0,0,1,2,1495521,4

In [6]:
person_2024.shape

(415549, 140)

In [23]:
print("person_2024_columns =",person_2024.columns.tolist())

person_2024_columns = ['Panel', 'File_Identification', 'Schedule', 'Quarter', 'Visit', 'Sector', 'State_UT_Code', 'District_Code', 'NSS_Region', 'Stratum', 'Sub_Stratum', 'Sub_Sample', 'FOD_Sub_Region', 'FSU', 'Sample_Sg_Sb_No', 'Second_Stage_Stratum_No', 'Sample_Household_Number', 'Person_Serial_No', 'Relationship_To_Head', 'Sex', 'Age', 'Marital_Status', 'General_Education_Level', 'Technical_Education_Level', 'Years_Formal_Education', 'Current_Attendance_Status', 'Vocational_Training', 'Training_Completed_365_Days', 'Field_Of_Training', 'Duration_Of_Training', 'Type_Of_Training', 'Training_Funding_Source', 'Principal_Status_Code', 'Principal_Industry_Code', 'Principal_Occupation_Code', 'Subsidiary_Work_Engagement', 'Principal_Workplace_Location', 'Principal_Enterprise_Type', 'Principal_Workers_Count', 'Principal_Job_Contract_Type', 'Principal_Paid_Leave', 'Principal_Social_Security', 'Principal_Product_Usage', 'Subsidiary_Status_Code', 'Subsidiary_Industry_Code', 'Subsidiary_Occupation_Code', 'Subsidiary_Workplace_Location', 'Subsidiary_Enterprise_Type', 'Subsidiary_Workers_Count', 'Subsidiary_Job_Contract_Type', 'Subsidiary_Paid_Leave', 'Subsidiary_Social_Security', 'Subsidiary_Product_Usage', 'Ever_Worked_365_Days', 'Principal_Duration', 'Subsidiary_Duration', 'Work_Search_Efforts', 'Unemployment_Duration', 'Ever_Worked', 'Reason_Not_Working', 'Main_Reason_Principal_Status', 'Day7_Act1_Status_Code', 'Day7_Act1_Industry_Code', 'Day7_Act1_Hours', 'Day7_Act1_Wage', 'Day7_Act2_Status_Code', 'Day7_Act2_Industry_Code', 'Day7_Act2_Hours', 'Day7_Act2_Wage', 'Day7_Total_Hours', 'Day7_Additional_Work_Hours', 'Day6_Act1_Status_Code', 'Day6_Act1_Industry_Code', 'Day6_Act1_Hours', 'Day6_Act1_Wage', 'Day6_Act2_Status_Code', 'Day6_Act2_Industry_Code', 'Day6_Act2_Hours', 'Day6_Act2_Wage', 'Day6_Total_Hours', 'Day6_Additional_Work_Hours', 'Day5_Act1_Status_Code', 'Day5_Act1_Industry_Code', 'Day5_Act1_Hours', 'Day5_Act1_Wage', 'Day5_Act2_Status_Code', 'Day5_Act2_Industry_Code', 'Day5_Act2_Hours', 'Day5_Act2_Wage', 'Day5_Total_Hours', 'Day5_Additional_Work_Hours', 'Day4_Act1_Status_Code', 'Day4_Act1_Industry_Code', 'Day4_Act1_Hours', 'Day4_Act1_Wage', 'Day4_Act2_Status_Code', 'Day4_Act2_Industry_Code', 'Day4_Act2_Hours', 'Day4_Act2_Wage', 'Day4_Total_Hours', 'Day4_Additional_Work_Hours', 'Day3_Act1_Status_Code', 'Day3_Act1_Industry_Code', 'Day3_Act1_Hours', 'Day3_Act1_Wage', 'Day3_Act2_Status_Code', 'Day3_Act2_Industry_Code', 'Day3_Act2_Hours', 'Day3_Act2_Wage', 'Day3_Total_Hours', 'Day3_Additional_Work_Hours', 'Day2_Act1_Status_Code', 'Day2_Act1_Industry_Code', 'Day2_Act1_Hours', 'Day2_Act1_Wage', 'Day2_Act2_Status_Code', 'Day2_Act2_Industry_Code', 'Day2_Act2_Hours', 'Day2_Act2_Wage', 'Day2_Total_Hours', 'Day2_Additional_Work_Hours', 'Day1_Act1_Status_Code', 'Day1_Act1_Industry_Code', 'Day1_Act1_Hours', 'Day1_Act1_Wage', 'Day1_Act2_Status_Code', 'Day1_Act2_Industry_Code', 'Day1_Act2_Hours', 'Day1_Act2_Wage', 'Day1_Total_Hours', 'Day1_Additional_Work_Hours', 'CWS_Status_Code', 'CWS_Industry_Code', 'CWS_Occupation_Code', 'CWS_Earnings_Salaried', 'CWS_Earnings_SelfEmployed', 'Ns_Count_Sector_Stratum_Substratum_Subsample', 'Ns_Count_Sector_Stratum_Substratum', 'Subsample_Multiplier', 'State_Sector_Stratum_Substra']

In [11]:
person_2023 = pd.read_csv("/Users/abhishek/Desktop/world-bank-indicators-project/PLFS_2023/cperv1.csv")

In [15]:
person_2023.head(200)

,panel_cperv1,FI_cperv1,B1q2_cperv1,qtr_cperv1,visit_cperv1,b1q3_cperv1,state_cperv1,distcode_cperv1,nss_region_cperv1,b1q5_cperv1,...,b6q8_act2_3pt7_cperv1,b6q5_cperv1,b6q6_cperv1,b6q7_cperv1,b6q9_cperv1,b6q10_cperv1,nss_cperv1,nsc_cperv1,mult_cperv1,no_qtr_cperv1
0,P3,CFVP3,104,Q7,V1,1,28,3,281,1,...,0,11,1.0,611.0,0,15000,1,2,2659089,2
1,P3,CFVP3,104,Q7,V1,1,28,3,281,1,...,0,99,NaN,NaN,0,0,1,2,2659089,2
2,P3,CFVP3,104,Q7,V1,1,28,3,281,1,...,0,99,NaN,NaN,0,0,1,2,2659089,2
3,P3,CFVP3,104,Q7,V1,1,28,3,281,1,...,0,99,NaN,NaN,0,0,1,2,2659089,2
4,P3,CFVP3,104,Q7,V1,1,28,3,281,1,...,0,93,NaN,NaN,0,0,1,2,2659089,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,P3,CFVP3,104,Q7,V1,1,28,1,281,1,...,0,51,1.0,921.0,0,0,1,2,2876499,2
196,P3,CFVP3,104,Q7,V1,1,28,1,281,1,...,0,81,NaN,NaN,0,0,1,2,2876499,2
197,P3,CFVP3,104,Q7,V1,1,28,1,281,1,...,0,92,NaN,NaN,0,0,1,2,2876499,2
198,P3,CFVP3,104,Q7,V1,1,28,1,281,1,...,0,51,1.0,921.0,0,0,1,2,2876499,2
199,P3,CFVP3,104,Q7,V1,1,28,1,281,1,...,0,81,NaN,NaN,0,0,1,2,2876499,2

In [12]:
person_2023.shape

(416332, 140)

In [25]:
print("person_2023_columns =",person_2023.columns.tolist())

person_2023_columns = ['panel_cperv1', 'FI_cperv1', 'B1q2_cperv1', 'qtr_cperv1', 'visit_cperv1', 'b1q3_cperv1', 'state_cperv1', 'distcode_cperv1', 'nss_region_cperv1', 'b1q5_cperv1', 'b1q6_cperv1', 'b1q11_cperv1', 'b1q12_cperv1', 'b1q1_cperv1', 'b1q13_cperv1', 'b1q14_cperv1', 'b1q15_cperv1', 'b4q1_cperv1', 'b4q4_cperv1', 'b4q5_cperv1', 'b4q6_perv1', 'b4q7_cperv1', 'b4q8_cperv1', 'b4q9_cperv1', 'b4q10_cperv1', 'b4q11_cperv1', 'b4q12_cperv1', 'b4pt1q3_cperv1', 'b4pt1q4_cperv1', 'b4pt1q5_cperv1', 'b4pt1q6_cperv1', 'b4pt1q7_cperv1', 'b5pt1q3_cperv1', 'b5pt1q5_cperv1', 'b5pt1q6_cperv1', 'b5pt1q7_cperv1', 'b5pt1q8_cperv1', 'b5pt1q9_cperv1', 'b5pt1q10_cperv1', 'b5pt1q11_cperv1', 'b5pt1q12_cperv1', 'b5pt1q13_cperv1', 'b5pt1q14_cperv1', 'b5pt2q3_cperv1', 'b5pt2q5_cperv1', 'b5pt2q6_cperv1', 'b5pt2q7_cperv1', 'b5pt2q8_cperv1', 'b5pt2q9_cperv1', 'b5pt2q10_cperv1', 'b5pt2q11_cperv1', 'b5pt2q12_cperv1', 'b5pt2q13_cperv1', 'b5pt3q5_cperv1', 'b5pt3q6_cperv1', 'b5pt3q7_cperv1', 'b5pt3q8_cperv1', 'b5pt3q9_cperv1', 'b5pt3q10_cperv1', 'b5pt3q11_cperv1', 'b5pt3q12_cperv1', 'b6q4_3pt1_cperv1', 'b6q5_3pt1_cperv1', 'b6q6_3pt1_cperv1', 'b6q9_3pt1_cperv1', 'b6q4_act2_3pt1_cperv1', 'b6q5_act2_3pt1_cperv1', 'b6q6_act2_3pt1_cperv1', 'b6q9_act2_3pt1_cperv1', 'b6q7_act2_3pt1_cperv1', 'b6q8_3pt1_cperv1', 'b6q4_3pt2_cperv1', 'b6q5_3pt2_cperv1', 'b6q6_3pt2_cperv1', 'b6q9_3pt2_cperv1', 'b6q4_act2_3pt2_cperv1', 'b6q5_act2_3pt2_cperv1', 'b6q6_act2_3pt2_cperv1', 'b6q9_act2_3pt2_cperv1', 'b6q7_3pt2_cperv1', 'b6q8_3pt2_cperv1', 'b6q4_3pt3_cperv1', 'b6q5_3pt3_cperv1', 'b6q6_3pt3_cperv1', 'b6q9_3pt3_cperv1', 'b6q4_act2_3pt3_cperv1', 'b6q5_act2_3pt3_cperv1', 'b6q6_act2_3pt3_cperv1', 'b6q9_act2_3pt3_cperv1', 'b6q7_3pt3_cperv1', 'b6q8_3pt3_cperv1', 'b6q4_3pt4_cperv1', 'b6q5_3pt4_cperv1', 'b6q6_3pt4_cperv1', 'b6q9_3pt4_cperv1', 'b6q4_act2_3pt4_cperv1', 'b6q5_act2_3pt4_cperv1', 'b6q6_act2_3pt4_cperv1', 'b6q9_act2_3pt4_cperv1', 'b6q7_3pt4_cperv1', 'b6q8_3pt4_cperv1', 'b6q4_3pt5_cperv1', 'b6q5_3pt5_cperv1', 'b6q6_3pt5_cperv1', 'b6q9_3pt5_cperv1', 'b6q4_act2_3pt5_cperv1', 'b6q5_act2_3pt5_cperv1', 'b6q6_act2_3pt5_cperv1', 'b6q9_act2_3pt5_cperv1', 'b6q7_3pt5_cperv1', 'b6q8_3pt5_cperv1', 'b6q4_3pt6_cperv1', 'b6q5_3pt6_cperv1', 'b6q6_3pt6_cperv1', 'b6q9_3pt6_cperv1', 'b6q4_act2_3pt6_cperv1', 'b6q5_act2_3pt6_cperv1', 'b6q6_act2_3pt6_cperv1', 'b6q9_act2_3pt6_cperv1', 'b6q7_3pt6_cperv1', 'b6q8_3pt6_cperv1', 'b6q4_3pt7_cperv1', 'b6q5_3pt7_cperv1', 'b6q6_3pt7_cperv1', 'b6q9_3pt7_cperv1', 'b6q4_act2_3pt7_cperv1', 'b6q5_act2_3pt7_cperv1', 'b6q6_act2_3pt7_cperv1', 'b6q9_act2_3pt7_cperv1', 'b6q7_act2_3pt7_cperv1', 'b6q8_act2_3pt7_cperv1', 'b6q5_cperv1', 'b6q6_cperv1', 'b6q7_cperv1', 'b6q9_cperv1', 'b6q10_cperv1', 'nss_cperv1', 'nsc_cperv1', 'mult_cperv1', 'no_qtr_cperv1']

In [16]:
person_2022 = pd.read_csv("/Users/abhishek/Desktop/world-bank-indicators-project/PLFS_2022/cperv1.csv")

In [18]:
person_2022.head(200)

,panel_cperv1,FI_cperv1,B1q2_cperv1,qtr_cperv1,visit_cperv1,b1q3_cperv1,state_cperv1,distcode_cperv1,nss_region_cperv1,b1q5_cperv1,...,b6q8_act2_3pt7_cperv1,b6q5_cperv1,b6q6_cperv1,b6q7_cperv1,b6q9_cperv1,b6q10_cperv1,nss_cperv1,nsc_cperv1,mult_cperv1,no_qtr_cperv1
0,P3,CFVP2,104,Q3,V1,1,28,2,281,1,...,0,11,1.0,611.0,0,12000,1,2,1293611.0,4
1,P3,CFVP2,104,Q3,V1,1,28,2,281,1,...,0,31,84.0,335.0,5000,0,1,2,1293611.0,4
2,P3,CFVP2,104,Q3,V1,1,28,2,281,1,...,0,21,1.0,611.0,0,0,1,2,1293611.0,4
3,P3,CFVP2,104,Q3,V1,1,28,2,281,1,...,0,31,84.0,335.0,12000,0,1,2,1293611.0,4
4,P3,CFVP2,104,Q3,V1,1,28,2,281,1,...,0,11,1.0,611.0,0,15000,1,2,1293611.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,P3,CFVP2,104,Q3,V1,1,28,2,281,1,...,0,21,1.0,611.0,0,0,1,2,2309669.0,4
196,P3,CFVP2,104,Q3,V1,1,28,2,281,1,...,0,91,NaN,NaN,0,0,1,2,2309669.0,4
197,P3,CFVP2,104,Q3,V1,1,28,2,281,1,...,0,51,1.0,921.0,0,0,1,2,1544591.0,4
198,P3,CFVP2,104,Q3,V1,1,28,2,281,1,...,0,31,86.0,322.0,10500,0,1,2,1544591.0,4
199,P3,CFVP2,104,Q3,V1,1,28,2,281,1,...,0,92,NaN,NaN,0,0,1,2,1544591.0,4

In [19]:
person_2022.shape

(424926, 140)

In [ ]:
print("person_2022_columns =",person_2022.columns.tolist())

### Key Finding: Inconsistent Naming Conventions
2024: Uses descriptive names (e.g., Principal_Occupation_Code, Subsample_Multiplier).

2022 & 2023: Use legacy NSS schedule names (e.g., b5pt1q6_cperv1 for Occupation, mult_cperv1 for Multiplier).

Action: We map the 2022/2023 columns to the 2024 schema before merging to ensure a consistent panel.